### ISSUE TITLE
npm run build 

### ISSUE THREAD

**Issue by undigitals** [PacktPublishing/Mastering-Node.js-Second-Edition#3]
The syntax of the command is incorrect.
masteringnodejs-collaborative@1.0.0 build: `mkdir -p static/dist/ && ./node_modules/.bin/browserify client.js -o static/dist/bundle.js`

**Comment by GlennGeenen** [comment]
Hey,

I run on linux and that command works fine for me, I guess the problem is that the mkdir is not working out for you when you run on Windows. The `mkdir -p static/dist/` just creates an empty dist directory within the static directory. You can manually create the dist directory and remove `mkdir -p static/dist/ && ` from the build command.

Another option can be to change the build command from `mkdir -p static/dist/` to `mkdir static\dist` on Windows, but I don't have Windows so I can't test that.

I hope that helped you.
